feat(lf): open_with

diff --git a/modules/home/lf/lfrc b/modules/home/lf/lfrc
--- a/modules/home/lf/lfrc
+++ b/modules/home/lf/lfrc
@@ -31,6 +31,37 @@ cmd open ${{
    esac
 }}
 
+cmd open_with ${{
+	ftype=$(xdg-mime query filetype "$f")
+	open_with=$(grep text/plain "${XDG_CONFIG_HOME:-$HOME/.config}/mimeapps.list" | head -n 1 | sed -e 's/^.*=//' -e 's/\.desktop;/\n/g' | fzf)
+
+	OLD_IFS=$IFS
+	IFS=:
+	for dir in $XDG_DATA_HOME:$XDG_DATA_DIRS; do
+		IFS=$OLD_IFS
+		# TODO search subdirs as well
+		desktop_entry="$dir/applications/$open_with.desktop" 
+		if [ -f "$desktop_entry" ]; then
+			echo INFO: reading from "$desktop_entry"
+			exe=$(awk '/^Exec=/{sub("^Exec=", ""); print}' "$desktop_entry")
+			[ -n "$exe" ] || exe=$(awk '/^TryExec=/{sub("^TryExec=", ""); print}' "$desktop_entry")
+			if [ -n "$exe" ]; then
+				# TODO shell escape $f
+				# TODO maybe use $fx for %F?
+				cmd=$(echo "$exe" | sed -e "s#%f#$f#g" -e "s#%F#$f#g" -e "s#%u#file://$f#g" -e "s#%U#file://$f#g" )
+				grep 'Terminal=true' "$desktop_entry" && exec $cmd
+				$cmd 2> /dev/null > /dev/null & disown
+				exit 0
+			else
+				echo "\x1b[31mERROR\x1b[0m:can't find Exec in $desktop_entry"
+			fi
+		fi
+	done
+
+	printf "\x1b[31mERROR\x1b[0m: can't find desktop entry $open_with.desktop\n"
+	exit 1
+}}
+
 cmd mkdir %{{
    printf "Directory Name: "
    read ans
@@ -312,6 +343,7 @@ map o $(xdg-open "$f" 1>/dev/null 2>/dev/null & disown)
 map O open_with
 map cv $gnvide
 map cd &LF_LEVEL=0 ${term:-xterm} -e "lf $PWD"
+map <c-g> $lazygit
 # }}
 
 # Archive Mappings {{
@@ -328,7 +360,7 @@ map tc clear_trash
 map tr restore_trash
 # }}
 
-# Broot Mapping {{
+# Fzf Mapping {{
 map f fzf_jump
 map F filter
 #map ss stripspace
@@ -420,7 +452,7 @@ map gee cd /mnt/ext
 # }}
 
 # funny mouse stuff {{
-map <m-1>
+# map <m-1>
 map <m-down> push 3j
 map <m-up> push 3k
 # }} }}
